#!/bin/bash

echo "Pulling latest changes"
hg pull

echo "Merging latest changes"
hg update

echo "Building..."
g++ -O2 `pkg-config --cflags --libs opencv` imagegrabber.cpp -o BeagleVision

echo "Running..."
./BeagleVision